#指定配置环境
spring:
  application:
    name: ${spring_application_name:console}
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 5000
    max-connections: 50000
  #开启压缩
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
mybatis:
  configuration:
    #使全局的映射器启用或禁用缓存。
    cache-enabled: false
    #设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 ) defalut:session
    local-cache-scope: session
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  #mybatis的xml路径
  mapper-locations: classpath*:com/**/dao/**/*DAO.xml,classpath*:com/**/dao/**/*${pagehelper.helperDialect}.xml,classpath*:com/**/dao/**/*DAO.xxml,classpath*:com/**/dao/**/*${pagehelper.helperDialect}.xxml
  #type-aliases-package: com.**.entity
  type-handlers-package: com.yuanian.infrastructure.util.service.typehandler
management:
  health:
    redis:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: ALWAYS
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      min-request-size: 1024
      mime-types: text/xml,application.xml,application/json
      enabled: true
    response:
      enabled: true
jasypt:
  encryptor:
    bootstrap: false
license:
  name: yuanian.lic
logging:
  config: classpath:log4j2.yml


