server:
  #指定项目端口
  port: ${server_port:8096}
  servlet:
    #指定项目路径
    context-path: /
spring:
  custom:
    feign:
      enabled: true
      opion:
        connectTimeoutMillis: 150000 #链接超时时间
        readTimeoutMillis: 150000 #响应超时时间，如果超过10秒没有接过发起下一次请求
      retry:
        period: 5000 #发起当前请求的时间间隔，单位毫秒
        maxPeriod: 5000 #发起当前请求的最大时间间隔，单位毫秒
        maxAttempts: 1 #最多请求次数，包括第一次
  redis:
    database: ${redis_database:0}
    host: ${redis_host:127.0.0.1}
    password: ${redis_password:}
    port: 6379
    jedis:
      pool:
        max-active: 500
        max-idle: 450
        min-idle: 0
        max-wait: 50000
    timeout: 100000
  datasource:
    druid:
      initial-size: 50
      min-idle: 5
      max-active: 200
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 25200000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        wall:
          config:
            comment-allow: true
            multi-statement-allow: true
      filters: stat,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      remove-abandoned: false
      remove-abandoned-timeout: 1800
      log-abandoned: true
      keep-alive: true
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql数据库相关配置
    driver-class-name: com.mysql.jdbc.Driver  #oracle.jdbc.OracleDriver（oracle驱动包）
    url: jdbc:mysql://127.0.0.1:3306/ecs?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    # dm 达梦数据库相关配置
    #    driver-class-name: dm.jdbc.driver.DmDriver
    #    url: jdbc:dm://192.168.0.66:5236/ECS_V20_HW
    #oracle数据库相关配置
#    driver-class-name: ${datasource_driver_class_name:oracle.jdbc.OracleDriver}
#    url: jdbc:${datasource_url:oracle:thin:@//192.168.58.135:1521/ecs}
    username: ${datasource_username:root}
    password: ${datasource_password:}
pagehelper:
  # mysql配置mysql、（oracle、dm）配置oracle
  helperDialect: ${datasource_type:mysql}
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true
yn:
  login:
    logout-target-url:  #推出登录后打开指定地址
    token-effective-time-web: 120 # 分钟
    token-effective-time-app: 10080 # 分钟
  login-auth-filter:
    isOpen: ${login_auth_enable:true}
    exclusionsList: #与 yn.loginAuthfilter.exclusions 配置互斥，exclusionsList优先
      - /console/v2/api/*
      - /logs/v2/*
      - /console/v2/system/getLoginBgType
      - /console/v2/user/sendKaptchaToEmail
      - /console/v2/user/getLoginNameByKaptcha
      - /console/v2/user/resetPwdByEmailCode
      - /console/client/user/getMsgLanCodeByLoginName
      - /console/client/ynCloud/login
      - /v2/api-docs*
      - /swagger-resources*
      - /webjars/*
      - /actuator
      - /actuator/*
      - /doc.html*
      - "*healthz"
      - /swagger-ui.html
      - /console/v2/sso/*
      - /sandbox/getSandboxList
      - /local/cache/*
      - /console/v2/login/*
      - /console/v2/system/getMobileConfigParam
      - /console/v2/user/getCaptcha
      - /console/v2/user/getPasswordRule
      - /console/v2/enterpriseInfo/getEnterpriseInfo
      - /console/client/task/receiveTask
      - /console/client/auth/ssoLogin
      - /console/client/auth/authenticate
      - /console/client/auth/systemUseable
      - /i18n/v2/language/getEnableLanguages
      - /i18n/v2/static/queryAllPageLanguages
      - /metadata/i18nWeb/customAction/getTranslationByKey
      - /metadata/i18nWeb/customAction/getTranslationByModule
      - /businessobject/v2/describe
      - /flow/runtime/clearFlowCaches
      - /masterdata/metadata/sysUser/*
      - /masterdata/metadata/sysUser
      - /masterdata/client/getSysUserById
      - /authority/client/data/getAuthData
      - /authority/client/*
      - /masterdata/dimSync/syncDims
      - /masterdata/userSync/syncUsersss
      - /console/v2/app/smartbi/loginSmartbi
      - /healtyzReport/middleware
      - /healtyzReport/deploy
      - /commonCallBack/*
      - /flow/v2/commonCallback/cardCallback
    token-security-enable: ${token_security_enable:false}
    token-security-use-black: ${token_security_use_black:false} #开启黑名单模式，黑名单开启后优先于白名单
    token-security-effective-time: ${token_security_effective_time:10000} #每次请求的有效时间，单位毫秒
    token-security-whitelist: #token安全校验白名单，此列表继承上面 exclusionsList 列表
      - "*/client/*"
      - /console/v2/notice/downloadAttachment
      - /excel/v2/exportExcel
    token-security-black-list: #token安全校验黑名单
      - /flow/v2/runtime/getHistorys
  e-mail-server: https://utestmsg.51ykb.com/msg/send
  replyEditorURL: /#/replyeditor
  filter:
    sign-verify-filter:
      enable: false
      include-url:
        - /xxx/xxx/xxx/xxx
    xss-filter:
      enable: true
      exclusions:
        - /metadata/pageDesignerPanels/customAction/updatePageDesignerPanel
        - /metadata/PluginsTrigger/customAction/addMetadataData
        - /metadata/PluginsTrigger/customAction/updateMetadataDataById
        - /metadata/pageDesignerPanels*
        - /metadata/plugins*
        - /metadata/pageDesignerTemplate*
        - /metadata/designerResource*
  signature:
    ssologin:
      secret-key: ssoLoginKey@20201218
      effective-time: 20  #秒
  database:
    # 数据库类型： mysql、oracle、dm（达梦）
    real-type: ${db_real_type:mysql}
  mq:
    enable: ${mq_enable:false}
    defaultBinder: rocket
    nameServers: ${mq_nameservers:192.168.2.237:9876}
    prefix: ${mq_prefix:dev172}
    reconsumeTimes: 3
    defaultSubjectPath: com.yuanian.auth.service.imp.LoginSubject
    # 补偿中心中最大重试次数
    maxReCompensationTimes: 3
    # 补偿日志保留天数
    logRetainDay: 15
    # 授权中心 MQ 是否接收控制台发出的： 用户角色、用户群组 和 角色权限集 三个关系数据,控制台服务必须关闭；业务系统引用授权中心模块、并需要使用权限服务、并且和控制台分库时需要开启
    consumerMessage: ${mq_consumermessage:true}
    # 消费组唯一标识，多个客户端需要同时消费同一个topic的消息时，多个客户端之间要配置不同的值。另外，授权中心做为sdk被业务线引用 并且 yn.mq.consumerMessage 值为 true 时，必须配置一个和控制台服务不一样的值
    consumerGroupFix: ${mq_consumergroupfix:ecs}
    compensator:
      open: true
      logRetainDay: 15
      maxReCompensationTimes: 3
  job:
    enable: ${job_enable:false}
    accessToken: ms-yuanian
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 3
      appname: ${job_appname:dev-ecs}
      port: ${job_port:9999}
      # 任务组唯一业务id，确保全局唯一
      businessid: ${job_businessid:dev-ecs}
      # 任务组名称
      title: ${job_title:dev-ecs}
    admin:
      addresses: ${job_admin_addresses:http://192.168.2.172/xxl-job-admin}
  dynamic-datasource: ${dynamic_datasource:false}  #开启动态多数据源，云多租户、沙盒、多应用情况需要开启
  app:
    multiple-app: ${multiple_app:false} #多应用开关
    multiple-app-check-dbkey-enabled: ${multiple_app_check_dbkey_enabled:true} #多应用数据源是否检查dbKey；默认true，multiple_app_service_name配置多个时，需要关闭；
    multiple-app-service-name: ${multiple_app_service_name:ecs} #多应用服务名称
    # multiple-app-copy-handler: ${multiple_app_copy_hanlder:YN_COPY_APP_JOB_HANDLER} #生成应用复制的调度任务的HANDLER名称，如果设置了这个参数，则需要提供调度任务消费方法。
  cloud:
    tenantMode: ${cloud_tenantmode:local}  # platform | local 多租户开关，platform开启
    server: ${cloud_server:http://ecs-cloudplatform-api.ecs-oracle-0220:12129/ecs-cloudplatform-api/}
    securityKey: 3g4l6bcs*1@.B7)p
    protocal: http
    loginAuth: login/verifyecstoken
    baseDriverDB: ${cloud_basedriverdb:mysql}
    baseVersion: 1.0
    isCloud: ${cloud_iscloud:false}
    syncUser: api/syncUser
    updateUserPwd: login/updatePassword
    dbLinkPrefix: _DbConn_
    dbKey: ${cloud_dbkey:ECS} #多租户、沙盒、多应用情况需配置
    #mysql
    dataSourceUrl: ${cloud_datasourceurl:jdbc:mysql://%s:%s/%s?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%%2B8}
    #oracle(SERVICE_NAME模式: jdbc:oracle:thin:@//%s:%s/%s ,SID模式: jdbc:oracle:thin:@%s:%s:%s)，
    #dataSourceUrl: "jdbc:oracle:thin:@//%s:%s/%s" #配置成SERVICE_NAME格式，兼容SERVICE_NAME与SID
  masterdata:
    addType: ${masterdata_addtype:enable}
  distribution:
    msg:
      pushnumber: 100
  businessflow:
    useThreadNumber: 20
  thread:
    primary:
      core_pool_size: 5
      keep_alive_seconds: 200
      max_pool_size: 20
      queue_capacity: 200
  file-store:
    type: fdfs
    class-name: com.yuanian.infrastructure.fileupload.service.impl.FdfsStoreService
  #    class-name: com.yuanian.infrastructure.fileupload.service.impl.OssFileStoreService
oss:
  #  目前有: minio ucloud huawei ali tencent
  ossType: minio
  #  该path前会自动加上一级目录,名称为:租户号或default, path的默认值是ecs
  path: ecs
  #  私有桶默认值为yn-private
  bucketName: yn-private
  #  公开桶默认值为yn-public
  publicBucketName: yn-public
  #  fileId中桶名和文件名之间的分割符,默认为"|",配置的时候注意yaml中的特殊字符需要用单引号包裹
  #  fileIdSeparator: '|'
  minio:
    endpoint: http://192.168.61.56:9944/
    accessKey: admin
    secretKey: admin123
fastdfs:
  isOpen: ${fastdfs_enable:true}
  connect_timeout: 5
  network_timeout: 30
  charset: ISO8859-1
  tracker_server: ${fastdfs_tracker_server:192.168.58.90:22122}
  http:
    tracker_http_port: 80
    anti_steal_token: no
    secret_key: FastDFS1234567890
#加密
jasypt:
  encryptor:
    bean: ${jasypt_bean_name:Sm4} #默认为jasyptStringEncryptor，Sm4为国密加密
  sm4:
    key: ${jasypt_sm4_key:1b32587a6e3a7ed31b174d7baa72656e} #Sm4加密的密钥值，要求长必须为32位16进制数
    iv: ${jasypt_sm4_iv:1b32587a6e3a7ed31b174d7baa72656e} #Sm4加密的向量值，要求长必须为32位16进制数
#设置ribbon过期时间
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  threadpool:
    default:
      coreSize: 10 #并发执行的核心线程数，默认10
      maxQueueSize: -1 #BlockingQueue的最大队列数 默认-1
      queueSizeRejectionThreshold: 5 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝;maxQueueSize=-1时，不起作用
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 240000
          semaphore:
            maxConcurrentRequests: 50
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 10000
        errorThresholdPercentage: 50
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 50
swagger:
  enable: ${swagger_enable:false} # swagger文档开关
com:
  yuanian:
    metadata:
      autoInitial: false
      localCacheEnable: ${LOCAL_CACHE_ENABLE:true} #是否启用元对象本地缓存
      localCacheExpireHours: ${LOCAL_CACHE_EXPIRE_HOURS:20} #本地缓存过期时间（单位:小时）
      controlByVersion: true
      securityCacheEnable: ${SECURITY_CACHE_ENABLE:true} #默认为true
    redisKeyPrefix: ${redis_key_prefix:ecs} #应用私有缓存
    fastjsonType: ${fastjson_type:fastjson2} #json序列化类型
    redisCommonKeyPrefix: ${redis_commonkey_prefix:ecs} #公共缓存
    cacheManager: RedisCacheManager
    redisCommonCacheNames: ${redis_commoncache_names:cp:authenticator,cp:metadataServiceMsg,cp:sandboxSwitch,cp:dbCommon,cp:i18nStaticDataC} #公共缓存CacheNames
    newUI: ${newUI:true}
    pdfBase: /tmp/ecs/pdf_tmp
    importCount: ${importCount:50}
    maxPdfFile: ${maxPdfFile:50}
    openTransPDF: ${openTransPDF:true}
#单体：无nacos时，请配置 *-service-url
console-service-url: ${console_service_url:http://console:8095}
discuss-service-url: ${discuss_service_url:http://console:8095}
centralized-console-service-url: ${centralized_console_service_url:http://console:8095}
#微服务：有nacos，请配置上面*-service-url为空，*-service-name：配置服务在注册中心地址
console-service-name: ${console_service_name:console}
discuss-service-name: ${discuss_service_name:console}
centralized-console-service-name: ${centralized_console_service_name:console}